export interface CapExemptEmployer {
  id: string;
  name: string;
  category: 'Higher Education' | 'Non-Profit Research' | 'Teaching Hospital / Medical Network' | 'National Laboratory (FFRDC)';
  city: string;
  state: string;
  stateCode: string;
  website: string;
  careersUrl: string;
  annualH1BVolume: string;
  topFields: string[];
  statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed' | 'INA § 214(g)(5)(B) Affiliated Non-Profit' | 'INA § 214(g)(5)(C) Research Org';
  notes: string;
}

export const CAP_EXEMPT_EMPLOYERS: CapExemptEmployer[] = [
  {
    id: 'ce-ca-001',
    name: 'Stanford University & SLAC National Accelerator Laboratory',
    category: 'Higher Education',
    city: 'Stanford',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.stanford.edu',
    careersUrl: 'https://careersearch.stanford.edu/',
    annualH1BVolume: '650+ Petitions/yr',
    topFields: ['AI / Computer Science', 'Bioengineering', 'Physics & SLAC', 'Postdocs', 'Data Science'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Premier research university with year-round H-1B filings and J-1 waiver support.'
  },
  {
    id: 'ce-ca-002',
    name: 'University of California, Berkeley (UC Berkeley)',
    category: 'Higher Education',
    city: 'Berkeley',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.berkeley.edu',
    careersUrl: 'https://jobs.berkeley.edu/',
    annualH1BVolume: '500+ Petitions/yr',
    topFields: ['Machine Learning', 'Economics', 'Chemistry', 'Biostatistics', 'Instructional Staff'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Public research flagship. High approval rate for postdoctoral and software research staff.'
  },
  {
    id: 'ce-ca-003',
    name: 'University of California, San Francisco (UCSF Health)',
    category: 'Teaching Hospital / Medical Network',
    city: 'San Francisco',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.ucsf.edu',
    careersUrl: 'https://sjobs.brassring.com/TGnewUI/Search/Home/HomeWithPreLoad?partnerid=6495&siteid=5226',
    annualH1BVolume: '450+ Petitions/yr',
    topFields: ['Clinical Research', 'Bioinformatics', 'Registered Nursing', 'Translational Medicine'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'Major medical research hospital. High green card transition rate for research fellows.'
  },
  {
    id: 'ce-ca-004',
    name: 'California Institute of Technology (Caltech) & NASA JPL',
    category: 'Higher Education',
    city: 'Pasadena',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.caltech.edu',
    careersUrl: 'https://www.caltech.edu/about/careers',
    annualH1BVolume: '380+ Petitions/yr',
    topFields: ['Aerospace Engineering', 'Robotics & JPL', 'Planetary Science', 'Quantum Computing'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Operates NASA Jet Propulsion Laboratory. Year-round cap-exempt processing.'
  },
  {
    id: 'ce-ca-005',
    name: 'Lawrence Berkeley National Laboratory (LBNL)',
    category: 'National Laboratory (FFRDC)',
    city: 'Berkeley',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.lbl.gov',
    careersUrl: 'https://jobs.lbl.gov/',
    annualH1BVolume: '220+ Petitions/yr',
    topFields: ['Supercomputing', 'Clean Energy Storage', 'Genomics & JGI', 'Materials Science'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'DOE National Laboratory managed by the University of California.'
  },
  {
    id: 'ce-ca-006',
    name: 'University of Southern California (USC & Keck Medicine)',
    category: 'Higher Education',
    city: 'Los Angeles',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.usc.edu',
    careersUrl: 'https://usccareers.usc.edu/',
    annualH1BVolume: '420+ Petitions/yr',
    topFields: ['Software Engineering', 'Information Sciences Institute (ISI)', 'Health Informatics'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Home of the Information Sciences Institute (ISI). Extensive H-1B hiring in AI/computing.'
  },
  {
    id: 'ce-ca-007',
    name: 'City of Hope Comprehensive Cancer Center',
    category: 'Teaching Hospital / Medical Network',
    city: 'Duarte',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.cityofhope.org',
    careersUrl: 'https://www.cityofhope.org/careers',
    annualH1BVolume: '180+ Petitions/yr',
    topFields: ['Immunotherapy', 'Hematology', 'Clinical Informatics', 'Laboratory Sciences'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'NCI-designated comprehensive cancer center with dedicated international visa sponsorship.'
  },
  {
    id: 'ce-ca-008',
    name: 'Scripps Research Institute',
    category: 'Non-Profit Research',
    city: 'La Jolla',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.scripps.edu',
    careersUrl: 'https://www.scripps.edu/careers/',
    annualH1BVolume: '200+ Petitions/yr',
    topFields: ['Chemical Biology', 'Immunology', 'Drug Discovery', 'Structural Biology'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'World-renowned non-profit biomedical research institute with top H-1B approval metrics.'
  },
  {
    id: 'ce-ca-009',
    name: 'Salk Institute for Biological Studies',
    category: 'Non-Profit Research',
    city: 'La Jolla',
    state: 'California',
    stateCode: 'CA',
    website: 'https://www.salk.edu',
    careersUrl: 'https://www.salk.edu/about/careers/',
    annualH1BVolume: '110+ Petitions/yr',
    topFields: ['Neuroscience', 'Plant Biology', 'Gene Expression', 'Cancer Biology'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'Independent non-profit research institution established by Jonas Salk.'
  },
  {
    id: 'ce-ma-001',
    name: 'Massachusetts Institute of Technology (MIT & Lincoln Laboratory)',
    category: 'Higher Education',
    city: 'Cambridge',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.mit.edu',
    careersUrl: 'https://hr.mit.edu/careers',
    annualH1BVolume: '700+ Petitions/yr',
    topFields: ['AI & Robotics', 'Lincoln Lab Systems', 'Materials Engineering', 'Computational Biology'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Global STEM epicenter. Zero lottery limit with expedited internal immigration counsel.'
  },
  {
    id: 'ce-ma-002',
    name: 'Harvard University & Wyss Institute',
    category: 'Higher Education',
    city: 'Cambridge',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.harvard.edu',
    careersUrl: 'https://hr.harvard.edu/careers',
    annualH1BVolume: '800+ Petitions/yr',
    topFields: ['Biomedical Sciences', 'Quantitative Economics', 'Public Health', 'Data Science'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Consistently ranks among top 5 national cap-exempt petitioners.'
  },
  {
    id: 'ce-ma-003',
    name: 'Broad Institute of MIT and Harvard',
    category: 'Non-Profit Research',
    city: 'Cambridge',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.broadinstitute.org',
    careersUrl: 'https://www.broadinstitute.org/careers',
    annualH1BVolume: '320+ Petitions/yr',
    topFields: ['Genomic Sequencing', 'CRISPR Technology', 'Software Engineering', 'Computational Biology'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'Non-profit biomedical genomic institute jointly founded by MIT and Harvard.'
  },
  {
    id: 'ce-ma-004',
    name: 'Dana-Farber Cancer Institute',
    category: 'Teaching Hospital / Medical Network',
    city: 'Boston',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.dana-farber.org',
    careersUrl: 'https://careers.dana-farber.org/',
    annualH1BVolume: '280+ Petitions/yr',
    topFields: ['Oncology Trials', 'Biostatistics', 'Molecular Genetics', 'Health IT'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'Harvard Medical School teaching affiliate with year-round H-1B and EB-2 sponsorship.'
  },
  {
    id: 'ce-ma-005',
    name: 'Massachusetts General Hospital (Mass General Brigham)',
    category: 'Teaching Hospital / Medical Network',
    city: 'Boston',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.massgeneral.org',
    careersUrl: 'https://www.massgeneralbrigham.org/en/about/careers',
    annualH1BVolume: '550+ Petitions/yr',
    topFields: ['Clinical Medicine', 'Neurobiology', 'Medical AI & Imaging', 'Clinical Informatics'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'Largest hospital-based research program in the United States.'
  },
  {
    id: 'ce-ma-006',
    name: 'Boston Children\'s Hospital',
    category: 'Teaching Hospital / Medical Network',
    city: 'Boston',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.childrenshospital.org',
    careersUrl: 'https://www.childrenshospital.org/career-opportunities',
    annualH1BVolume: '190+ Petitions/yr',
    topFields: ['Pediatric Research', 'Gene Therapy', 'Stem Cell Biology', 'Healthcare Data Analytics'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: '#1 ranked pediatric teaching hospital with prominent international physician/scientist program.'
  },
  {
    id: 'ce-ma-007',
    name: 'Northeastern University',
    category: 'Higher Education',
    city: 'Boston',
    state: 'Massachusetts',
    stateCode: 'MA',
    website: 'https://www.northeastern.edu',
    careersUrl: 'https://careers.hrm.northeastern.edu/',
    annualH1BVolume: '290+ Petitions/yr',
    topFields: ['Experiential AI', 'Cybersecurity', 'Bioinformatics', 'Data Analytics', 'Academic Faculty'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Major global research institution with extensive co-op programs and cap-exempt staff hires.'
  },
  {
    id: 'ce-ny-001',
    name: 'Columbia University & Irving Medical Center',
    category: 'Higher Education',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    website: 'https://www.columbia.edu',
    careersUrl: 'https://opportunities.columbia.edu/',
    annualH1BVolume: '720+ Petitions/yr',
    topFields: ['Data Science Institute', 'Biomedicine', 'Finance & Economics', 'Software Research'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Ivy League university in Manhattan with heavy international hiring across STEM and medicine.'
  },
  {
    id: 'ce-ny-002',
    name: 'Memorial Sloan Kettering Cancer Center (MSKCC)',
    category: 'Teaching Hospital / Medical Network',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    website: 'https://www.mskcc.org',
    careersUrl: 'https://careers.mskcc.org/',
    annualH1BVolume: '460+ Petitions/yr',
    topFields: ['Computational Oncology', 'Immunology', 'Biostatistics', 'Software Engineering'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'World-renowned cancer institution with exceptional track record in green card sponsorships.'
  },
  {
    id: 'ce-ny-003',
    name: 'New York University (NYU & NYU Langone Health)',
    category: 'Higher Education',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    website: 'https://www.nyu.edu',
    careersUrl: 'https://www.nyu.edu/about/careers-at-nyu.html',
    annualH1BVolume: '680+ Petitions/yr',
    topFields: ['Courant Institute (Math/CS)', 'Center for Data Science', 'Health Informatics'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Major global university. Year-round cap-exempt visa filing across academic & hospital campuses.'
  },
  {
    id: 'ce-ny-004',
    name: 'Cornell University & Weill Cornell Medicine',
    category: 'Higher Education',
    city: 'Ithaca & New York',
    state: 'New York',
    stateCode: 'NY',
    website: 'https://www.cornell.edu',
    careersUrl: 'https://hr.cornell.edu/jobs',
    annualH1BVolume: '540+ Petitions/yr',
    topFields: ['Cornell Tech (Roosevelt Island)', 'Biomedical Research', 'Agricultural Sciences'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Dual campuses in Ithaca and Manhattan (Cornell Tech / Weill Cornell).'
  },
  {
    id: 'ce-ny-005',
    name: 'Brookhaven National Laboratory (BNL)',
    category: 'National Laboratory (FFRDC)',
    city: 'Upton',
    state: 'New York',
    stateCode: 'NY',
    website: 'https://www.bnl.gov',
    careersUrl: 'https://jobs.bnl.gov/',
    annualH1BVolume: '190+ Petitions/yr',
    topFields: ['Nuclear Physics (RHIC)', 'Synchrotron Light Source (NSLS-II)', 'Quantum Information'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'DOE multipurpose national laboratory located on Long Island.'
  },
  {
    id: 'ce-ny-006',
    name: 'Cold Spring Harbor Laboratory (CSHL)',
    category: 'Non-Profit Research',
    city: 'Cold Spring Harbor',
    state: 'New York',
    stateCode: 'NY',
    website: 'https://www.cshl.edu',
    careersUrl: 'https://www.cshl.edu/about-us/careers/',
    annualH1BVolume: '95+ Petitions/yr',
    topFields: ['Genetics & Genomics', 'Neuroscience', 'Plant Biology', 'Bioinformatics'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'Historic private non-profit biomedical research institution.'
  },
  {
    id: 'ce-tx-001',
    name: 'University of Texas at Austin (UT Austin & TACC)',
    category: 'Higher Education',
    city: 'Austin',
    state: 'Texas',
    stateCode: 'TX',
    website: 'https://www.utexas.edu',
    careersUrl: 'https://eats.hr.utexas.edu/jobs',
    annualH1BVolume: '520+ Petitions/yr',
    topFields: ['Texas Advanced Computing Center (TACC)', 'Semiconductors', 'AI Research', 'Engineering'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Top tier research university with Texas Advanced Computing Center supercomputer facility.'
  },
  {
    id: 'ce-tx-002',
    name: 'UT MD Anderson Cancer Center',
    category: 'Teaching Hospital / Medical Network',
    city: 'Houston',
    state: 'Texas',
    stateCode: 'TX',
    website: 'https://www.mdanderson.org',
    careersUrl: 'https://www.mdanderson.org/about-md-anderson/careers.html',
    annualH1BVolume: '580+ Petitions/yr',
    topFields: ['Cancer Immunology', 'Genomics', 'Biostatistics', 'Clinical Operations', 'Nursing'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: '#1 ranked cancer hospital in the world. Extremely active in H-1B and Green Card sponsorships.'
  },
  {
    id: 'ce-tx-003',
    name: 'Texas A&M University System',
    category: 'Higher Education',
    city: 'College Station',
    state: 'Texas',
    stateCode: 'TX',
    website: 'https://www.tamu.edu',
    careersUrl: 'https://jobs.tamu.edu/',
    annualH1BVolume: '480+ Petitions/yr',
    topFields: ['Petroleum & Energy', 'Aerospace Engineering', 'Agricultural Research', 'Data Science'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Massive public university system with extensive federal research contracts.'
  },
  {
    id: 'ce-tx-004',
    name: 'Houston Methodist Hospital System',
    category: 'Teaching Hospital / Medical Network',
    city: 'Houston',
    state: 'Texas',
    stateCode: 'TX',
    website: 'https://www.houstonmethodist.org',
    careersUrl: 'https://www.houstonmethodistcareers.org/',
    annualH1BVolume: '230+ Petitions/yr',
    topFields: ['Cardiovascular Research', 'Translational Medicine', 'Registered Nursing (EB-3)', 'Health IT'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'Top ranked hospital network affiliated with Weill Cornell Medicine & Texas A&M.'
  },
  {
    id: 'ce-tx-005',
    name: 'UT Southwestern Medical Center',
    category: 'Teaching Hospital / Medical Network',
    city: 'Dallas',
    state: 'Texas',
    stateCode: 'TX',
    website: 'https://www.utsouthwestern.edu',
    careersUrl: 'https://jobs.utsouthwestern.edu/',
    annualH1BVolume: '360+ Petitions/yr',
    topFields: ['Molecular Biology', 'Biomedical Imaging', 'Clinical Trials', 'Neuroscience'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'Prominent medical center with 6 Nobel laureates in faculty history.'
  },
  {
    id: 'ce-il-001',
    name: 'University of Illinois Urbana-Champaign (UIUC & NCSA)',
    category: 'Higher Education',
    city: 'Urbana-Champaign',
    state: 'Illinois',
    stateCode: 'IL',
    website: 'https://illinois.edu',
    careersUrl: 'https://jobs.illinois.edu/',
    annualH1BVolume: '490+ Petitions/yr',
    topFields: ['National Center for Supercomputing (NCSA)', 'Electrical Engineering', 'Robotics'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Top 5 computer science school. Birthplace of Mosaic web browser & NCSA supercomputing.'
  },
  {
    id: 'ce-il-002',
    name: 'Argonne National Laboratory',
    category: 'National Laboratory (FFRDC)',
    city: 'Lemont',
    state: 'Illinois',
    stateCode: 'IL',
    website: 'https://www.anl.gov',
    careersUrl: 'https://www.anl.gov/careers',
    annualH1BVolume: '260+ Petitions/yr',
    topFields: ['Exascale Supercomputing (Aurora)', 'Battery Science', 'Advanced Photon Source', 'AI'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'DOE multidisciplinary lab operated by UChicago Argonne LLC.'
  },
  {
    id: 'ce-il-003',
    name: 'Fermi National Accelerator Laboratory (Fermilab)',
    category: 'National Laboratory (FFRDC)',
    city: 'Batavia',
    state: 'Illinois',
    stateCode: 'IL',
    website: 'https://www.fnal.gov',
    careersUrl: 'https://jobs.fnal.gov/',
    annualH1BVolume: '140+ Petitions/yr',
    topFields: ['Particle Physics', 'Neutrino Research (DUNE)', 'Quantum Computing', 'Cryogenics'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'America\'s premier particle physics and accelerator laboratory.'
  },
  {
    id: 'ce-il-004',
    name: 'University of Chicago (UChicago & UChicago Medicine)',
    category: 'Higher Education',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    website: 'https://www.uchicago.edu',
    careersUrl: 'https://www.uchicago.edu/jobs/',
    annualH1BVolume: '470+ Petitions/yr',
    topFields: ['Economics & Data', 'Biological Sciences', 'Quantum Engineering', 'Clinical Medicine'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'World-renowned research university and academic medical center in Hyde Park.'
  },
  {
    id: 'ce-il-005',
    name: 'Northwestern University & Northwestern Medicine',
    category: 'Higher Education',
    city: 'Evanston & Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    website: 'https://www.northwestern.edu',
    careersUrl: 'https://www.northwestern.edu/hr/careers/',
    annualH1BVolume: '410+ Petitions/yr',
    topFields: ['Nanotechnology', 'Feinberg School of Medicine', 'AI in Health', 'Kellogg Analytics'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Major private research university with dual campuses in Evanston and downtown Chicago.'
  },
  {
    id: 'ce-wa-001',
    name: 'University of Washington (UW & UW Medicine)',
    category: 'Higher Education',
    city: 'Seattle',
    state: 'Washington',
    stateCode: 'WA',
    website: 'https://www.washington.edu',
    careersUrl: 'https://hr.uw.edu/jobs/',
    annualH1BVolume: '590+ Petitions/yr',
    topFields: ['Paul G. Allen School of CSE', 'Global Health', 'Genome Sciences', 'UW Medical Center'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Consistently ranks in top 3 national recipients of federal research grants.'
  },
  {
    id: 'ce-wa-002',
    name: 'Fred Hutchinson Cancer Center (Fred Hutch)',
    category: 'Non-Profit Research',
    city: 'Seattle',
    state: 'Washington',
    stateCode: 'WA',
    website: 'https://www.fredhutch.org',
    careersUrl: 'https://www.fredhutch.org/en/careers.html',
    annualH1BVolume: '210+ Petitions/yr',
    topFields: ['Immunotherapy', 'Viral Oncology', 'Computational Biology', 'Vaccine Development'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'Independent non-profit research institution pioneering bone marrow transplantation.'
  },
  {
    id: 'ce-wa-003',
    name: 'Pacific Northwest National Laboratory (PNNL)',
    category: 'National Laboratory (FFRDC)',
    city: 'Richland',
    state: 'Washington',
    stateCode: 'WA',
    website: 'https://www.pnnl.gov',
    careersUrl: 'https://www.pnnl.gov/careers',
    annualH1BVolume: '180+ Petitions/yr',
    topFields: ['Power Grid Cybersecurity', 'Atmospheric Science', 'Nuclear Chemistry', 'Data Analytics'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'DOE national lab managed by Battelle Memorial Institute.'
  },
  {
    id: 'ce-wa-004',
    name: 'Allen Institute (AI, Brain Science, Cell Science)',
    category: 'Non-Profit Research',
    city: 'Seattle',
    state: 'Washington',
    stateCode: 'WA',
    website: 'https://alleninstitute.org',
    careersUrl: 'https://alleninstitute.org/careers/',
    annualH1BVolume: '90+ Petitions/yr',
    topFields: ['Allen Institute for AI (AI2)', 'Brain Mapping', 'Cell Biology', 'Open Science Tools'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'Founded by Paul G. Allen. Home to the Allen Institute for Artificial Intelligence (AI2).'
  },
  {
    id: 'ce-md-001',
    name: 'Johns Hopkins University & Applied Physics Laboratory (JHU / APL)',
    category: 'Higher Education',
    city: 'Baltimore & Laurel',
    state: 'Maryland',
    stateCode: 'MD',
    website: 'https://www.jhu.edu',
    careersUrl: 'https://jobs.jhu.edu/',
    annualH1BVolume: '890+ Petitions/yr',
    topFields: ['APL Space & Defense', 'Biomedical Engineering', 'Bloomberg School of Public Health'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: '#1 U.S. university in total research expenditures for 44 consecutive years.'
  },
  {
    id: 'ce-md-002',
    name: 'University of Maryland, College Park (UMD & UMIACS)',
    category: 'Higher Education',
    city: 'College Park',
    state: 'Maryland',
    stateCode: 'MD',
    website: 'https://www.umd.edu',
    careersUrl: 'https://ejobs.umd.edu/',
    annualH1BVolume: '390+ Petitions/yr',
    topFields: ['Quantum Institute (Joint Quantum Institute)', 'Cybersecurity', 'AI & Vision (UMIACS)'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Close research proximity to NIST, NASA Goddard, and NIH.'
  },
  {
    id: 'ce-md-003',
    name: 'Howard Hughes Medical Institute (HHMI & Janelia Research Campus)',
    category: 'Non-Profit Research',
    city: 'Chevy Chase & Ashburn',
    state: 'Maryland',
    stateCode: 'MD',
    website: 'https://www.hhmi.org',
    careersUrl: 'https://www.hhmi.org/careers',
    annualH1BVolume: '130+ Petitions/yr',
    topFields: ['Neuroscience', 'Optical Microscopy', 'Structural Biology', 'Biomedical Computation'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'Leading non-profit medical research organization and research philanthropy.'
  },
  {
    id: 'ce-pa-001',
    name: 'University of Pennsylvania (UPenn & Penn Medicine)',
    category: 'Higher Education',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    website: 'https://www.upenn.edu',
    careersUrl: 'https://www.hr.upenn.edu/Penn-Careers',
    annualH1BVolume: '610+ Petitions/yr',
    topFields: ['mRNA Vaccine Technology', 'Penn Medicine Oncology', 'Robotics (GRASP Lab)', 'Finance'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Ivy League university and academic health system (Nobel Prize in mRNA research).'
  },
  {
    id: 'ce-pa-002',
    name: 'Carnegie Mellon University (CMU & SEI)',
    category: 'Higher Education',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateCode: 'PA',
    website: 'https://www.cmu.edu',
    careersUrl: 'https://www.cmu.edu/jobs/',
    annualH1BVolume: '450+ Petitions/yr',
    topFields: ['Robotics Institute', 'Machine Learning Dept', 'Software Engineering Institute (SEI)'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Global leader in Computer Science, Artificial Intelligence, and Autonomous Systems.'
  },
  {
    id: 'ce-pa-003',
    name: 'University of Pittsburgh & UPMC Health System',
    category: 'Teaching Hospital / Medical Network',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateCode: 'PA',
    website: 'https://www.pitt.edu',
    careersUrl: 'https://www.join.pitt.edu/',
    annualH1BVolume: '510+ Petitions/yr',
    topFields: ['Transplantation Immunology', 'Pharmacology', 'Biomedical Informatics', 'Nursing'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'Massive healthcare enterprise (UPMC) partnering with the University of Pittsburgh.'
  },
  {
    id: 'ce-nc-001',
    name: 'Duke University & Duke Health',
    category: 'Higher Education',
    city: 'Durham',
    state: 'North Carolina',
    stateCode: 'NC',
    website: 'https://www.duke.edu',
    careersUrl: 'https://careers.duke.edu/',
    annualH1BVolume: '530+ Petitions/yr',
    topFields: ['Duke Clinical Research Institute (DCRI)', 'Bioinformatics', 'Cancer Institute', 'Data Science'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Anchor institution of the Research Triangle with massive clinical trials network.'
  },
  {
    id: 'ce-nc-002',
    name: 'University of North Carolina at Chapel Hill (UNC)',
    category: 'Higher Education',
    city: 'Chapel Hill',
    state: 'North Carolina',
    stateCode: 'NC',
    website: 'https://www.unc.edu',
    careersUrl: 'https://unc.peopleadmin.com/',
    annualH1BVolume: '380+ Petitions/yr',
    topFields: ['Gillings School of Global Public Health', 'Lineberger Cancer Center', 'Genomics'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Top-ranked public research university with year-round cap-exempt visa filings.'
  },
  {
    id: 'ce-nc-003',
    name: 'RTI International (Research Triangle Institute)',
    category: 'Non-Profit Research',
    city: 'Research Triangle Park',
    state: 'North Carolina',
    stateCode: 'NC',
    website: 'https://www.rti.org',
    careersUrl: 'https://www.rti.org/careers',
    annualH1BVolume: '140+ Petitions/yr',
    topFields: ['Global Health Solutions', 'Environmental Engineering', 'Statistical Analysis', 'Survey Research'],
    statutoryBasis: 'INA § 214(g)(5)(C) Research Org',
    notes: 'One of the world\'s leading non-profit research institutes with 6,000+ staff.'
  },
  {
    id: 'ce-ga-001',
    name: 'Georgia Institute of Technology (Georgia Tech & GTRI)',
    category: 'Higher Education',
    city: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    website: 'https://www.gatech.edu',
    careersUrl: 'https://careers.gatech.edu/',
    annualH1BVolume: '560+ Petitions/yr',
    topFields: ['GTRI Applied Research', 'Aerospace Engineering', 'AI & Machine Learning', 'Industrial Systems'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Includes Georgia Tech Research Institute (GTRI) with massive applied R&D programs.'
  },
  {
    id: 'ce-ga-002',
    name: 'Emory University & Emory Healthcare',
    category: 'Higher Education',
    city: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    website: 'https://www.emory.edu',
    careersUrl: 'https://www.hr.emory.edu/careers/',
    annualH1BVolume: '430+ Petitions/yr',
    topFields: ['Winship Cancer Institute', 'Infectious Diseases', 'Vaccine Research', 'Health Economics'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Adjacent to CDC headquarters with premier infectious disease and clinical programs.'
  },
  {
    id: 'ce-mn-001',
    name: 'Mayo Clinic & Mayo Clinic Health System',
    category: 'Teaching Hospital / Medical Network',
    city: 'Rochester',
    state: 'Minnesota',
    stateCode: 'MN',
    website: 'https://www.mayoclinic.org',
    careersUrl: 'https://jobs.mayoclinic.org/',
    annualH1BVolume: '780+ Petitions/yr',
    topFields: ['Clinical Specialties', 'Artificial Intelligence in Medicine', 'Genomics', 'Registered Nursing (EB-3)'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: '#1 hospital in the nation. Operates one of the largest cap-exempt visa programs in the US.'
  },
  {
    id: 'ce-mn-002',
    name: 'University of Minnesota Twin Cities',
    category: 'Higher Education',
    city: 'Minneapolis',
    state: 'Minnesota',
    stateCode: 'MN',
    website: 'https://twin-cities.umn.edu',
    careersUrl: 'https://humanresources.umn.edu/jobs',
    annualH1BVolume: '370+ Petitions/yr',
    topFields: ['Chemical Engineering', 'Biotechnology', 'Medical Devices', 'Agricultural Science'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Major Big Ten research university with extensive patents and corporate tech transfer.'
  },
  {
    id: 'ce-oh-001',
    name: 'Cleveland Clinic Health System',
    category: 'Teaching Hospital / Medical Network',
    city: 'Cleveland',
    state: 'Ohio',
    stateCode: 'OH',
    website: 'https://my.clevelandclinic.org',
    careersUrl: 'https://jobs.clevelandclinic.org/',
    annualH1BVolume: '620+ Petitions/yr',
    topFields: ['Cardiology & Thoracic Surgery', 'Genomic Medicine', 'Clinical Data Analytics', 'Nursing'],
    statutoryBasis: 'INA § 214(g)(5)(B) Affiliated Non-Profit',
    notes: 'World-renowned medical center with dedicated foreign medical graduate sponsorship.'
  },
  {
    id: 'ce-mi-001',
    name: 'University of Michigan, Ann Arbor & Michigan Medicine',
    category: 'Higher Education',
    city: 'Ann Arbor',
    state: 'Michigan',
    stateCode: 'MI',
    website: 'https://umich.edu',
    careersUrl: 'https://careers.umich.edu/',
    annualH1BVolume: '610+ Petitions/yr',
    topFields: ['Automotive & Robotics', 'Bioengineering', 'Michigan Medicine', 'Social Science Research'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: '#1 public research university in research volume ($1.8B+ annual research spend).'
  },
  {
    id: 'ce-in-001',
    name: 'Purdue University',
    category: 'Higher Education',
    city: 'West Lafayette',
    state: 'Indiana',
    stateCode: 'IN',
    website: 'https://www.purdue.edu',
    careersUrl: 'https://careers.purdue.edu/',
    annualH1BVolume: '390+ Petitions/yr',
    topFields: ['Semiconductor Fabrication', 'Aerospace Engineering', 'Agricultural Biotechnology', 'Data Science'],
    statutoryBasis: 'INA § 214(g)(5)(A) Higher Ed',
    notes: 'Top STEM powerhouse leading national microelectronics and CHIPS Act initiatives.'
  }
];
