import { JobPosting } from './types';

export const INITIAL_JOBS: JobPosting[] = [
  // ==========================================
  // 1. GLOBAL REMOTE JOBS (PAID IN USD - FORM W-8BEN)
  // ==========================================
  {
    id: 'job-rem-001',
    title: 'Customer Happiness Engineer (Global Remote - Paid in USD)',
    company: 'Automattic (WordPress.com / WooCommerce)',
    location: 'Remote (Worldwide - Contractor / W-8BEN)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Customer Support & Helpdesk',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 55000,
    salaryMax: 78000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Work from anywhere in the world helping WordPress.com and WooCommerce users troubleshoot plugins, CSS styling, hosting configurations, and payment gateways. Fully distributed team across 90+ countries with bi-annual global meetups.',
    requirements: [
      'Strong written English fluency and clear customer empathy',
      'Solid foundational understanding of WordPress, HTML, and basic CSS',
      'Curiosity to troubleshoot web technical issues asynchronously',
      'Self-driven work ethic with no local supervision required'
    ],
    skills: ['WordPress', 'CSS', 'HTML', 'Customer Support', 'Troubleshooting', 'Asynchronous Communication'],
    sourceUrl: 'https://automattic.com/work-with-us/',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-002',
    title: 'AI Prompt Evaluator & Data Annotation Specialist (Paid in USD)',
    company: 'Scale AI / Outlier.ai',
    location: 'Remote (Worldwide - Independent Contractor)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Data, AI Training & Annotation',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 42000,
    salaryMax: 65000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Train cutting-edge Large Language Models (LLMs) by grading model responses for accuracy, reasoning, coding logic, and factuality. Flexible weekly hours with direct USD bank deposits via Wise or PayPal.',
    requirements: [
      'Fluent English reading and critical analytical evaluation skills',
      'Attention to detail and ability to spot factual hallucinations',
      'Educational background in STEM, Linguistics, Computer Science, or Humanities',
      'Reliable high-speed internet and desktop computer'
    ],
    skills: ['Data Annotation', 'AI Prompt Engineering', 'Critical Thinking', 'English Writing', 'Fact-Checking'],
    sourceUrl: 'https://scale.com/careers',
    atsType: 'greenhouse',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-003',
    title: 'Technical Support Specialist (Zapier Workflows & APIs)',
    company: 'Zapier',
    location: 'Remote (Worldwide - 100% Distributed)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Customer Support & Helpdesk',
    experienceLevel: 'Mid Level',
    salaryMin: 62000,
    salaryMax: 88000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Help global creators and business owners automate workflows across 5,000+ integrated web apps. Diagnose Webhooks, API request payloads, OAuth authentication, and Zapier code steps.',
    requirements: [
      'Experience with REST APIs, JSON data structures, and Webhooks',
      'Outstanding written communication in English',
      'Experience diagnosing technical SaaS bugs and integrations',
      'Ability to thrive in a 100% remote asynchronous environment'
    ],
    skills: ['APIs', 'JSON', 'Webhooks', 'Zapier', 'Technical Support', 'Troubleshooting'],
    sourceUrl: 'https://zapier.com/jobs',
    atsType: 'greenhouse',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-rem-004',
    title: 'Global Virtual Executive Assistant & Operations Coordinator',
    company: 'Athena Executive Services',
    location: 'Remote (Worldwide - Remote USD Contract)',
    city: 'New York',
    state: 'NY',
    isRemote: true,
    category: 'Virtual Assistant & Admin',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 38000,
    salaryMax: 54000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Support high-growth US tech executives and venture capitalists with strategic scheduling, email inbox triaging, travel planning, and specialized research. Full training provided in modern AI productivity tools.',
    requirements: [
      'Fluent verbal and written English communication',
      'Meticulous organizational skills and proactive calendar management',
      'Proficiency in Google Suite, Notion, and Slack',
      'High professional discretion and dependable follow-through'
    ],
    skills: ['Executive Assistance', 'Calendar Management', 'Google Workspace', 'Communication', 'Research'],
    sourceUrl: 'https://www.athenago.com',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-rem-005',
    title: 'Full-Stack Next.js & TypeScript Engineer (Global Contractor)',
    company: 'Supabase Ecosystem Partners',
    location: 'Remote (Worldwide)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 70000,
    salaryMax: 110000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Build modern serverless web applications and real-time database interfaces using Next.js App Router, Tailwind CSS, and Supabase PostgreSQL. Work asynchronously with a high-trust international engineering crew.',
    requirements: [
      '3+ years professional experience with TypeScript, React, and Next.js App Router',
      'Solid understanding of PostgreSQL schemas, RLS policies, and REST/GraphQL APIs',
      'Portfolio of live deployed web projects'
    ],
    skills: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Supabase'],
    sourceUrl: 'https://supabase.com/careers',
    atsType: 'lever',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-006',
    title: 'Senior Cloud DevOps & Site Reliability Engineer (Global Remote)',
    company: 'GitLab',
    location: 'Remote (Worldwide - Remote Contract)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Software & Tech',
    experienceLevel: 'Senior / Lead',
    salaryMin: 95000,
    salaryMax: 145000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Architect, monitor, and scale distributed Kubernetes clusters running across AWS and GCP for millions of active developers worldwide. Manage CI/CD pipelines, Terraform infrastructure, and incident response.',
    requirements: [
      '5+ years managing production Kubernetes, Docker, and Linux environments',
      'Expertise in Terraform, Ansible, and Infrastructure-as-Code (IaC)',
      'Demonstrated expertise with Prometheus, Grafana, and Datadog observability'
    ],
    skills: ['Kubernetes', 'Terraform', 'AWS', 'GCP', 'CI/CD', 'Prometheus', 'Linux'],
    sourceUrl: 'https://about.gitlab.com/jobs/',
    atsType: 'greenhouse',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-rem-007',
    title: 'Social Media & Content Marketing Specialist (Remote USD)',
    company: 'Buffer',
    location: 'Remote (Worldwide)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Marketing & Sales',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 48000,
    salaryMax: 68000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Create engaging short-form video scripts, educational social carousels, and case studies highlighting social media strategies for small businesses and creators globally. 4-day workweek company culture.',
    requirements: [
      'Proven portfolio of published social media content (TikTok, YouTube, LinkedIn)',
      'Excellent English copywriting and storytelling skills',
      'Familiarity with Canva, Figma, or basic video editing software'
    ],
    skills: ['Content Marketing', 'Copywriting', 'Social Media Strategy', 'Canva', 'Video Editing'],
    sourceUrl: 'https://buffer.com/journey',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-rem-008',
    title: 'Creative Graphic & UI Designer (Contractor - Paid in USD)',
    company: 'Superside',
    location: 'Remote (Worldwide - Flexible Hours)',
    city: 'Wilmington',
    state: 'DE',
    isRemote: true,
    category: 'Operations & Other',
    experienceLevel: 'Mid Level',
    salaryMin: 42000,
    salaryMax: 62000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Join an elite global design team delivering high-impact branding, digital ad creatives, presentation decks, and web assets for top US enterprise brands like Amazon, Meta, and Salesforce.',
    requirements: [
      'Strong online design portfolio demonstrating branding and digital graphic design',
      'Mastery of Figma, Adobe Photoshop, and Illustrator',
      'Ability to deliver fast-turnaround creative assets following strict brand guidelines'
    ],
    skills: ['Figma', 'Adobe Illustrator', 'Photoshop', 'UI Design', 'Branding'],
    sourceUrl: 'https://www.superside.com/careers',
    atsType: 'lever',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    isFeatured: false
  },

  // ==========================================
  // 2. CAP-EXEMPT H-1B JOBS (NO ANNUAL LOTTERY - UNIVERSITIES & RESEARCH INSTITUTES)
  // ==========================================
  {
    id: 'job-cap-001',
    title: 'Clinical Data Coordinator & Research Associate (Cap-Exempt H-1B)',
    company: 'Johns Hopkins Medicine',
    location: 'Baltimore, MD (Full Visa Sponsorship Provided)',
    city: 'Baltimore',
    state: 'MD',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 62000,
    salaryMax: 82000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Coordinate patient registry data, clinical trial documentation, and IRB regulatory submissions across oncology clinical trials. Position qualifies for immediate year-round Cap-Exempt H-1B visa sponsorship with no lottery cap.',
    requirements: [
      'Bachelor’s or Master’s in Public Health, Health Informatics, Biology, or related field',
      'Familiarity with REDCap, Epic EHR, and FDA clinical trial guidelines',
      'Attention to detail in patient health records and HIPAA compliance'
    ],
    skills: ['REDCap', 'Epic EHR', 'Clinical Trials', 'Data Management', 'Biostatistics', 'HIPAA'],
    sourceUrl: 'https://jobs.jhu.edu',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-cap-002',
    title: 'Bioinformatics Research Programmer (Lottery-Exempt H-1B)',
    company: 'Stanford University School of Medicine',
    location: 'Stanford, CA',
    city: 'Stanford',
    state: 'CA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 92000,
    salaryMax: 128000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Develop Python/R genomic processing pipelines for single-cell RNA sequencing (scRNA-seq) and spatial transcriptomics. Work with leading geneticists to analyze cancer immunology datasets with guaranteed Cap-Exempt H-1B sponsorship.',
    requirements: [
      'Master’s or PhD in Bioinformatics, Computational Biology, or Computer Science',
      'Proficiency in Python (Biopython, Scanpy), R (Seurat), and Linux HPC environments',
      'Experience with Nextflow or Snakemake workflow managers'
    ],
    skills: ['Python', 'R', 'Bioinformatics', 'Nextflow', 'Genomics', 'Linux HPC'],
    sourceUrl: 'https://cardinalcareers.stanford.edu/',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-cap-003',
    title: 'Machine Learning Research Specialist (Cap-Exempt H-1B Sponsor)',
    company: 'Broad Institute of MIT and Harvard',
    location: 'Cambridge, MA',
    city: 'Cambridge',
    state: 'MA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 95000,
    salaryMax: 135000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Apply deep neural networks and transformer architectures to predict molecular interactions, drug binding affinities, and protein structures. Direct non-profit research institution status enables immediate year-round H-1B filing.',
    requirements: [
      'Master’s or PhD in Computer Science, Machine Learning, or Computational Chemistry',
      'Expertise in PyTorch, JAX, CUDA acceleration, and high-performance computing',
      'Demonstrated research track record (NeurIPS, ICML, Nature Biotech, or equivalent)'
    ],
    skills: ['PyTorch', 'Machine Learning', 'Transformers', 'Deep Learning', 'Python', 'CUDA'],
    sourceUrl: 'https://www.broadinstitute.org/careers',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-cap-004',
    title: 'High-Performance Scientific Computing Engineer (Cap-Exempt H-1B)',
    company: 'Oak Ridge National Laboratory (ORNL)',
    location: 'Oak Ridge, TN',
    city: 'Oak Ridge',
    state: 'TN',
    isRemote: false,
    category: 'Engineering',
    experienceLevel: 'Mid Level',
    salaryMin: 88000,
    salaryMax: 122000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Optimize scientific simulation codes for the Frontier exascale supercomputer. Support international researchers running complex quantum, materials science, and climate simulation workloads.',
    requirements: [
      'Master’s degree in Computer Engineering, Computational Science, or Physics',
      'Proficiency in C++, Fortran, MPI, OpenMP, and GPU programming (CUDA/HIP)',
      'Experience optimizing parallel algorithms on large-scale supercomputers'
    ],
    skills: ['C++', 'CUDA', 'MPI', 'Parallel Computing', 'Linux', 'HPC'],
    sourceUrl: 'https://jobs.ornl.gov',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-cap-005',
    title: 'Research Systems Engineer & HPC Cluster Specialist',
    company: 'Purdue University',
    location: 'West Lafayette, IN',
    city: 'West Lafayette',
    state: 'IN',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 72000,
    salaryMax: 94000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Maintain and scale enterprise academic Linux supercomputing clusters used by 4,000+ graduate researchers. Purdue sponsors qualified international engineers under university Cap-Exempt status.',
    requirements: [
      'Bachelor’s or Master’s in Computer Science, Information Technology, or related discipline',
      'Hands-on experience with Linux administration (RHEL, Ubuntu), Bash scripting, and Slurm scheduler',
      'Knowledge of network storage (NFS, Ceph, Lustre) and containerization (Singularity/Docker)'
    ],
    skills: ['Linux', 'Slurm', 'Bash', 'Docker', 'HPC', 'Cluster Administration'],
    sourceUrl: 'https://careers.purdue.edu',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    isFeatured: false
  },

  // ==========================================
  // 3. HEALTHCARE & NURSING (SCHEDULE A DIRECT GREEN CARDS & H-1B)
  // ==========================================
  {
    id: 'job-nurse-001',
    title: 'Registered Nurse - Critical Care ICU (Schedule A EB-3 Green Card Sponsor)',
    company: 'Cleveland Clinic Health System',
    location: 'Cleveland, OH (Direct Green Card Sponsorship)',
    city: 'Cleveland',
    state: 'OH',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Mid Level',
    salaryMin: 82000,
    salaryMax: 115000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Ranked #2 hospital in the United States. Cleveland Clinic directly sponsors qualified international RNs with NCLEX-RN for EB-3 Permanent Residency (Green Cards) with zero PERM labor certification delay under US DOL Schedule A rules. Full relocation and licensing assistance provided.',
    requirements: [
      'BSN (Bachelor of Science in Nursing) degree',
      'Passed US NCLEX-RN exam or hold active US State RN License / VisaScreen certificate',
      'Minimum 18 months acute care hospital experience in ICU, CCU, or Medical-Surgical'
    ],
    skills: ['ICU Nursing', 'Critical Care', 'NCLEX-RN', 'Patient Care', 'Ventilator Management', 'ACLS'],
    sourceUrl: 'https://jobs.clevelandclinic.org',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-nurse-002',
    title: 'Staff Registered Nurse - Emergency & Telemetry (EB-3 Visa & Relocation)',
    company: 'HCA Healthcare Network',
    location: 'Nashville, TN (Multi-State Placements)',
    city: 'Nashville',
    state: 'TN',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 76000,
    salaryMax: 98000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Direct EB-3 immigrant visa sponsorship for international nurses across 180+ hospitals in Florida, Texas, Tennessee, and Virginia. Comprehensive onboarding, competitive shift differentials, and family green card sponsorship.',
    requirements: [
      'Nursing degree (BSN or equivalent) from an accredited program',
      'Active NCLEX-RN score or CGFNS VisaScreen certification',
      'English proficiency (IELTS Academic 6.5+ or TOEFL iBT 83+)'
    ],
    skills: ['Emergency Nursing', 'Telemetry', 'BLS/ACLS', 'Patient Triage', 'NCLEX-RN'],
    sourceUrl: 'https://careers.hcahealthcare.com',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-nurse-003',
    title: 'International Nurse Transition Program (Direct US Hospital Sponsorship)',
    company: 'Avant Healthcare Professionals',
    location: 'Orlando, FL (Nationwide US Hospital Placements)',
    city: 'Orlando',
    state: 'FL',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 72000,
    salaryMax: 96000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Comprehensive US clinical cultural transition program for international nurses. Covers 100% of US Green Card immigration legal fees, flight airfare, free US housing upon arrival, and competitive hospital salaries.',
    requirements: [
      'Registered Nurse with 1+ years of bedside hospital experience',
      'Passed NCLEX-RN or currently studying for NCLEX exam',
      'Commitment to work in a top US health system for standard placement term'
    ],
    skills: ['Bedside Nursing', 'NCLEX Prep', 'Patient Assessment', 'US Clinical Protocols'],
    sourceUrl: 'https://avanthealthcare.com',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 17).toISOString(),
    isFeatured: false
  },

  // ==========================================
  // 4. TECH & CORPORATE H-1B SPONSORS (COMMERCIAL LEADERS)
  // ==========================================
  {
    id: 'job-tech-001',
    title: 'Software Development Engineer - Distributed Cloud Services',
    company: 'Microsoft',
    location: 'Redmond, WA',
    city: 'Redmond',
    state: 'WA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 118000,
    salaryMax: 165000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Design and build high-throughput microservices for Microsoft Azure. Strong history of H-1B sponsorship, F-1 STEM OPT extensions, and direct Green Card PERM processing for qualified engineers.',
    requirements: [
      'BSc or MSc in Computer Science, Software Engineering, or related STEM field',
      'Proficiency in C#, Java, C++, or Go with data structures and algorithms mastery',
      'Understanding of multithreading, REST APIs, and distributed systems architecture'
    ],
    skills: ['C#', 'Azure', 'Distributed Systems', 'Go', 'Data Structures', 'Cloud Computing'],
    sourceUrl: 'https://careers.microsoft.com',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-tech-002',
    title: 'AI / Machine Learning Engineer (PyTorch & LLM Inference)',
    company: 'NVIDIA',
    location: 'Santa Clara, CA',
    city: 'Santa Clara',
    state: 'CA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 145000,
    salaryMax: 215000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Optimize deep learning inference kernels (TensorRT-LLM, Triton Inference Server) on next-generation GPU architectures. NVIDIA actively sponsors H-1B visas and O-1 extraordinary ability petitions for top talent.',
    requirements: [
      'MSc or PhD in Computer Science, Computer Engineering, or Electrical Engineering',
      'Expertise with CUDA, C++, PyTorch, and TensorRT optimization',
      'Understanding of modern transformer model parallelization (Megatron-LM, DeepSpeed)'
    ],
    skills: ['CUDA', 'PyTorch', 'TensorRT', 'C++', 'GPU Optimization', 'LLMs'],
    sourceUrl: 'https://www.nvidia.com/en-us/about-nvidia/careers/',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-tech-003',
    title: 'Junior Quantitative Research Analyst (F-1 STEM OPT & H-1B)',
    company: 'Goldman Sachs',
    location: 'New York, NY',
    city: 'New York',
    state: 'NY',
    isRemote: false,
    category: 'Business & Finance',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 110000,
    salaryMax: 150000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'OPT/CPT Friendly',
    sponsorshipConfidence: 'high',
    description: 'Develop mathematical models for pricing derivatives, assessing algorithmic risk, and analyzing macroeconomic data. Actively hires STEM graduates with full support for F-1 STEM OPT and H-1B lottery filings.',
    requirements: [
      'Degree in Financial Engineering, Mathematics, Statistics, Physics, or CS',
      'Proficiency in Python (NumPy, Pandas, SciPy), SQL, and statistical modeling',
      'Understanding of stochastic calculus, probability, and financial derivatives'
    ],
    skills: ['Python', 'SQL', 'Financial Modeling', 'Statistics', 'Risk Management'],
    sourceUrl: 'https://www.goldmansachs.com/careers',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 13).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-tech-004',
    title: 'Cloud Infrastructure Solutions Architect (H-1B Transfer & Sponsorship)',
    company: 'Amazon Web Services (AWS)',
    location: 'Seattle, WA',
    city: 'Seattle',
    state: 'WA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 125000,
    salaryMax: 175000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Help global enterprise customers architect fault-tolerant, secure, and cost-effective workloads on AWS. AWS is among the top H-1B sponsors in the United States with dedicated immigration legal teams.',
    requirements: [
      '3+ years experience designing cloud architectures and distributed applications',
      'Deep knowledge of AWS services (EC2, S3, RDS, Lambda, VPC, IAM)',
      'Strong technical advisory and customer presentation skills'
    ],
    skills: ['AWS', 'Cloud Architecture', 'Terraform', 'Networking', 'Security'],
    sourceUrl: 'https://www.amazon.jobs',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(),
    isFeatured: false
  },

  // ==========================================
  // 5. STUDY WITH JOBS / PART-TIME GRADUATE ASSISTANTSHIPS & ON-CAMPUS CPT/OPT
  // ==========================================
  {
    id: 'job-stu-001',
    title: 'Graduate Student Instructor / Teaching Assistant (100% Tuition Waiver + Salary)',
    company: 'University of Michigan (GEO Union)',
    location: 'Ann Arbor, MI (On-Campus F-1 Eligible)',
    city: 'Ann Arbor',
    state: 'MI',
    isRemote: false,
    category: 'Operations & Other',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 36000,
    salaryMax: 44000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'OPT/CPT Friendly',
    sponsorshipConfidence: 'high',
    description: 'Teach recitation sections, grade exams, and hold office hours for undergraduate courses (20 hrs/week). Includes 100% full tuition waiver (worth $55,000/yr) plus union-negotiated living stipend and comprehensive health insurance.',
    requirements: [
      'Enrolled or admitted to a graduate degree program (Master’s or PhD) at U-M',
      'Demonstrated mastery in subject area (Computer Science, Math, Economics, Biology, etc.)',
      'Clear verbal English communication skills for classroom instruction'
    ],
    skills: ['Teaching', 'Curriculum Support', 'Student Mentoring', 'Subject Mastery'],
    sourceUrl: 'https://rackham.umich.edu/funding/',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-stu-002',
    title: 'Graduate Research Assistant in AI & Robotics (Full Tuition Waiver + Stipend)',
    company: 'Georgia Institute of Technology',
    location: 'Atlanta, GA (On-Campus F-1 Eligible)',
    city: 'Atlanta',
    state: 'GA',
    isRemote: false,
    category: 'Engineering',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 32000,
    salaryMax: 40000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'OPT/CPT Friendly',
    sponsorshipConfidence: 'high',
    description: 'Conduct funded robotics and autonomous systems research. Covers 100% out-of-state tuition (students pay only nominal $25/semester fee) plus a bi-weekly living stipend.',
    requirements: [
      'Admitted or applying to Georgia Tech College of Computing / Engineering',
      'Background in ROS (Robot Operating System), C++, Python, or computer vision',
      'Strong academic research motivation'
    ],
    skills: ['Robotics', 'ROS', 'Python', 'C++', 'Computer Vision', 'Research'],
    sourceUrl: 'https://grad.gatech.edu/',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    isFeatured: true
  }
];

let dynamicJobs: JobPosting[] = [...INITIAL_JOBS];

export function getJobsList(): JobPosting[] {
  return dynamicJobs;
}

export function addOrUpdateJobs(newJobs: JobPosting[]) {
  const existingMap = new Map<string, JobPosting>();
  dynamicJobs.forEach(j => existingMap.set(j.id, j));
  newJobs.forEach(j => existingMap.set(j.id, j));
  dynamicJobs = Array.from(existingMap.values());
  dynamicJobs.sort((a, b) => new Date(b.postedDate).getTime() - new Date(a.postedDate).getTime());
}

export function findJobById(id: string): JobPosting | undefined {
  return dynamicJobs.find(j => j.id === id);
}
