import { JobPosting } from './types';

export const INITIAL_JOBS: JobPosting[] = [
  // --- US REMOTE CONTRACTOR / W-8BEN (GLOBAL APPLICANTS WELCOME) ---
  {
    id: 'job-rem-001',
    title: 'Customer Happiness Engineer (Global Remote - Paid in USD)',
    company: 'Automattic (WordPress.com / WooCommerce)',
    location: 'Remote (Worldwide - Work from Anywhere)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Customer Support & Helpdesk',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 48000,
    salaryMax: 70000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Automattic is 100% distributed and hires in 90+ countries. Help millions of global WordPress and WooCommerce creators succeed via chat and email support. No formal CS degree required. Payouts processed directly via international contractor agreements (W-8BEN) in US Dollars.',
    requirements: [
      'Empathetic, clear written communication in English',
      'Curiosity about the web, basic HTML/CSS, and troubleshooting websites',
      'High self-motivation for asynchronous distributed remote teamwork',
      'Fast and reliable home internet connection'
    ],
    skills: ['Customer Support', 'WordPress', 'HTML/CSS Basics', 'Written English', 'Zendesk'],
    sourceUrl: 'https://automattic.com/work-with-us',
    atsType: 'greenhouse',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-002',
    title: 'AI Prompt Evaluator & Data Annotation Specialist (Contract)',
    company: 'Scale AI / Outlier.ai',
    location: 'Remote (Global - Direct Weekly PayPal/Bank Payout)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Data, AI Training & Annotation',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 35000,
    salaryMax: 55000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Train cutting-edge Large Language Models (LLMs) used by top US AI companies. Review AI outputs for factual truth, logical reasoning, safety, and coherence. Open to international candidates from diverse academic backgrounds with strong English mastery.',
    requirements: [
      'Strong logical thinking, grammar, and analytical evaluation skills',
      'Fluency in written and reading English',
      'Ability to strictly adhere to complex rubric guidelines',
      'Personal computer and stable internet connection'
    ],
    skills: ['AI Evaluation', 'Data Annotation', 'Analytical Thinking', 'Fact-Checking', 'LLM Training'],
    sourceUrl: 'https://scale.com/careers',
    atsType: 'lever',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-003',
    title: 'Technical Customer Support Specialist (Zapier Workflows)',
    company: 'Zapier',
    location: 'Remote (Anywhere Worldwide)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Customer Support & Helpdesk',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 52000,
    salaryMax: 76000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Zapier empowers automation for millions. Support users with webhook setups, API connections, and workflow troubleshooting. Fully remote company offering generous annual learning stipends, home-office equipment budget, and USD compensation.',
    requirements: [
      'Superb customer empathy and technical troubleshooting mindset',
      'Understanding of basic web concepts (APIs, webhooks, SaaS platforms)',
      'Experience in asynchronous collaboration (Slack, Loom, Coda)',
      'Problem-solving resourcefulness'
    ],
    skills: ['Zapier', 'APIs', 'Customer Support', 'Troubleshooting', 'SaaS Tools'],
    sourceUrl: 'https://zapier.com/jobs',
    atsType: 'ashby',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-004',
    title: 'Junior Frontend Support Developer (Vue.js & Markdown)',
    company: 'GitLab',
    location: 'Remote (Global Contractor via EOR)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Software & Tech',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 58000,
    salaryMax: 84000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Join the world’s largest all-remote DevOps company. Fix frontend UI issues, maintain design documentation, and assist with open-source community merge requests. Flexible working hours with global peer mentorship.',
    requirements: [
      'Foundational knowledge of HTML, modern CSS, JavaScript, and Vue.js / React',
      'Comfortable using Git, GitHub, and command line tools',
      'High-standard documentation habits and transparent communication'
    ],
    skills: ['Vue.js', 'JavaScript', 'Git', 'CSS/Tailwind', 'Open Source'],
    sourceUrl: 'https://gitlab.com/jobs',
    atsType: 'greenhouse',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-rem-005',
    title: 'Global Virtual Executive Assistant & Operations Coordinator',
    company: 'Athena Executive Services',
    location: 'Remote (Worldwide - Remote Contract)',
    city: 'New York',
    state: 'NY',
    isRemote: true,
    category: 'Virtual Assistant & Admin',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 38000,
    salaryMax: 54000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Support high-growth US tech executives and venture capitalists with calendar management, email triaging, travel itineraries, and specialized research. Full training provided in cutting-edge AI productivity tools.',
    requirements: [
      'Native or bilingual English fluency (verbal & written)',
      'Meticulous organizational skills and calendar management',
      'Proficiency in Google Suite, Notion, and Slack',
      'Professional discretion and proactive work ethic'
    ],
    skills: ['Executive Assistance', 'Calendar Management', 'Google Workspace', 'Communication', 'Research'],
    sourceUrl: 'https://athenago.com/careers',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    isFeatured: false
  },

  // --- CAP-EXEMPT H-1B JOBS (NO ANNUAL LOTTERY RISK!) ---
  {
    id: 'job-cap-001',
    title: 'Clinical Data Coordinator & Research Associate (Cap-Exempt H-1B)',
    company: 'Johns Hopkins Medicine',
    location: 'Baltimore, MD (Full Visa Sponsorship Provided)',
    city: 'Baltimore',
    state: 'MD',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 54000,
    salaryMax: 72000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Johns Hopkins is an academic non-profit medical research institution eligible for Cap-Exempt H-1B petitions (exempt from the H-1B lottery cap). Support clinical trial tracking, patient data verification, and regulatory submissions.',
    requirements: [
      'Bachelor’s in Health Sciences, Biology, Public Health, or related field',
      'Familiarity with EDC systems, REDCap, and clinical trial protocols',
      'Strong attention to regulatory compliance and patient data privacy (HIPAA)',
      'Open to international candidates holding F-1 OPT or requiring immediate H-1B'
    ],
    skills: ['Clinical Research', 'REDCap', 'Data Management', 'Good Clinical Practice', 'Health Sciences'],
    sourceUrl: 'https://jobs.jhu.edu',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-cap-002',
    title: 'Bioinformatics Research Programmer (Lottery-Exempt H-1B)',
    company: 'Stanford University School of Medicine',
    location: 'Stanford, CA (Hybrid / On-Campus)',
    city: 'Stanford',
    state: 'CA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 88000,
    salaryMax: 125000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Stanford University sponsors H-1B petitions year-round without being subject to the lottery cap. Build genomics analysis pipelines, process next-generation sequencing data, and collaborate with leading scientists.',
    requirements: [
      'Degree in Computational Biology, Computer Science, or Bioinformatics',
      'Proficiency in Python, R, Nextflow, and Linux/Unix cluster environments',
      'Experience with biological data visualization and genomics pipelines'
    ],
    skills: ['Python', 'Bioinformatics', 'R', 'Genomics', 'Linux/Bash', 'Nextflow'],
    sourceUrl: 'https://careers.stanford.edu',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-cap-003',
    title: 'Research Systems Engineer & High-Performance Computing Specialist',
    company: 'Purdue University',
    location: 'West Lafayette, IN (Cap-Exempt Visa Sponsor)',
    city: 'West Lafayette',
    state: 'IN',
    isRemote: false,
    category: 'Engineering',
    experienceLevel: 'Mid Level',
    salaryMin: 76000,
    salaryMax: 108000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Maintain university supercomputing clusters and support faculty research simulations. Purdue provides complete lottery-exempt H-1B sponsorship and paths for long-term university faculty/staff residency.',
    requirements: [
      'BSc or MSc in Computer Engineering, Electrical Engineering, or CS',
      'Hands-on experience with Linux cluster administration, Slurm, and Docker',
      'Scripting proficiency in Python or Bash'
    ],
    skills: ['Linux', 'HPC Clusters', 'Slurm', 'Python', 'Networking', 'Docker'],
    sourceUrl: 'https://careers.purdue.edu',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    isFeatured: false
  },

  // --- HEALTHCARE & REGISTERED NURSING (DIRECT SCHEDULE A GREEN CARD) ---
  {
    id: 'job-nurse-001',
    title: 'Registered Nurse - Critical Care / Medical Surgical (Schedule A EB-3 Green Card)',
    company: 'Cleveland Clinic Health System',
    location: 'Cleveland, OH (Full Relocation + Green Card Sponsor)',
    city: 'Cleveland',
    state: 'OH',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Mid Level',
    salaryMin: 82000,
    salaryMax: 118000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'Cleveland Clinic sponsors international nurses for direct US Permanent Residency (EB-3 Green Card via Schedule A exemption). Zero PERM labor certification delay. Includes relocation allowance, sign-on bonuses, and NCLEX licensure endorsement.',
    requirements: [
      'BSN Degree in Nursing or accredited equivalent',
      'Valid NCLEX-RN passing result (or actively scheduled)',
      '1+ years hospital inpatient bedside nursing experience',
      'English proficiency certification (IELTS Academic / TOEFL iBT / VisaScreen)'
    ],
    skills: ['NCLEX-RN', 'Bedside Care', 'Critical Care', 'Patient Safety', 'IV Therapy', 'EMR/Epic'],
    sourceUrl: 'https://jobs.clevelandclinic.org',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-nurse-002',
    title: 'Staff Registered Nurse - Emergency & Telemetry Units (EB-3 Visa)',
    company: 'HCA Healthcare Network',
    location: 'Nashville, TN (Visa Sponsorship Available)',
    city: 'Nashville',
    state: 'TN',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Mid Level',
    salaryMin: 78000,
    salaryMax: 112000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Direct hire hospital nursing opportunity with comprehensive US immigration processing. HCA Healthcare is America’s largest private healthcare network, sponsoring foreign nurses through qualified legal counsel.',
    requirements: [
      'Nursing degree (BSN preferred)',
      'NCLEX-RN certification',
      'Passionate about emergency and acute inpatient healthcare',
      'Valid passport and eligibility for US immigration processing'
    ],
    skills: ['Emergency Care', 'Telemetry', 'Triage', 'Patient Assessment', 'NCLEX-RN'],
    sourceUrl: 'https://hcahealthcare.com/careers',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    isFeatured: false
  },

  // --- BIG TECH & STEM OPT JOBS ---
  {
    id: 'job-tech-001',
    title: 'Software Development Engineer - Distributed Cloud Services',
    company: 'Microsoft',
    location: 'Redmond, WA (Hybrid / Remote)',
    city: 'Redmond',
    state: 'WA',
    isRemote: true,
    category: 'Software & Tech',
    experienceLevel: 'Senior / Lead',
    salaryMin: 145000,
    salaryMax: 215000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Build enterprise-grade cloud systems on Microsoft Azure. Microsoft provides complete immigration sponsorship (H-1B transfer, STEM OPT extension, and Day-1 PERM Green Card processing).',
    requirements: [
      '3+ years experience with C#, Java, Python, or TypeScript',
      'Strong understanding of algorithms, data structures, and microservices architecture',
      'Bachelor’s or Master’s in Computer Science or related STEM degree'
    ],
    skills: ['C#', 'Azure', 'TypeScript', 'Distributed Systems', 'Microservices', 'Docker'],
    sourceUrl: 'https://careers.microsoft.com',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    isFeatured: true
  },
  {
    id: 'job-tech-002',
    title: 'Junior Quantitative Research Analyst (F-1 STEM OPT & H-1B)',
    company: 'Goldman Sachs',
    location: 'New York, NY (Financial District)',
    city: 'New York',
    state: 'NY',
    isRemote: false,
    category: 'Business & Finance',
    experienceLevel: 'Entry Level / Junior',
    salaryMin: 120000,
    salaryMax: 165000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'OPT/CPT Friendly',
    sponsorshipConfidence: 'high',
    description: 'Join Goldman Sachs Quantitative Investment Strategies team. Develop statistical predictive models, clean high-frequency market datasets, and automate risk analytics.',
    requirements: [
      'Degree in Quantitative Finance, Mathematics, Physics, Statistics, or Computer Science',
      'Advanced Python (Pandas, NumPy, Scikit-Learn) and SQL skills',
      'Curiosity for financial markets and algorithmic trading'
    ],
    skills: ['Python', 'SQL', 'Financial Modeling', 'Statistics', 'Risk Analysis'],
    sourceUrl: 'https://www.goldmansachs.com/careers',
    atsType: 'direct',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(),
    isFeatured: false
  },
  {
    id: 'job-tech-003',
    title: 'AI / Machine Learning Engineer (PyTorch & LLM Inference)',
    company: 'NVIDIA',
    location: 'Santa Clara, CA (or Austin, TX)',
    city: 'Santa Clara',
    state: 'CA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 160000,
    salaryMax: 240000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Accelerate the world’s most advanced AI models using NVIDIA CUDA and TensorRT. Full visa support for STEM OPT grads, H-1B transfers, and expedited EB-2 green cards.',
    requirements: [
      'Strong C++ and Python development experience',
      'In-depth understanding of Transformer architectures, PyTorch, and CUDA optimization',
      'MS or PhD in Computer Science, AI, or Electrical Engineering'
    ],
    skills: ['CUDA', 'PyTorch', 'C++', 'Python', 'LLM Inference', 'GPU Computing'],
    sourceUrl: 'https://www.nvidia.com/en-us/about-nvidia/careers/',
    atsType: 'workday',
    postedDate: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    isFeatured: true
  },
  // --- ADDITIONAL 2026 VERIFIED HIGH-DEMAND OPPORTUNITIES ---
  {
    id: 'job-rem-005',
    title: 'Senior Cloud DevOps & Site Reliability Engineer (Global Remote)',
    company: 'GitLab',
    location: 'Remote (Worldwide - Contractor W-8BEN / Direct USD)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Software & Tech',
    experienceLevel: 'Senior / Lead',
    salaryMin: 110000,
    salaryMax: 155000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'GitLab is 100% remote. Lead containerized cloud infrastructure on Kubernetes, Terraform, and GCP/AWS. Manage CI/CD pipelines and high-availability architecture with zero physical office requirements.',
    requirements: [
      '5+ years experience managing production Kubernetes clusters',
      'Proficiency with Terraform, Prometheus, Grafana, and CI/CD pipelines',
      'Strong background in Linux kernel performance and distributed systems',
      'Excellent asynchronous English communication'
    ],
    skills: ['Kubernetes', 'Terraform', 'Docker', 'AWS', 'GCP', 'CI/CD', 'Go/Python'],
    sourceUrl: 'https://about.gitlab.com/jobs',
    atsType: 'greenhouse',
    postedDate: new Date().toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-006',
    title: 'Full-Stack Next.js & TypeScript Engineer (W-8BEN Contractor)',
    company: 'Supabase Ecosystem Partners',
    location: 'Remote (Anywhere Worldwide)',
    city: 'San Francisco',
    state: 'CA',
    isRemote: true,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 75000,
    salaryMax: 105000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Build modern serverless web applications using Next.js 15, React, Tailwind CSS, and PostgreSQL. Paid directly in USD twice monthly via Wise or Deel.',
    requirements: [
      '3+ years professional experience with TypeScript, React, and Next.js App Router',
      'Strong understanding of PostgreSQL, RLS policies, and REST/GraphQL APIs',
      'Portfolio of live deployed web projects'
    ],
    skills: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Supabase'],
    sourceUrl: 'https://supabase.com/careers',
    atsType: 'lever',
    postedDate: new Date().toISOString(),
    isFeatured: true
  },
  {
    id: 'job-rem-007',
    title: 'Executive Virtual Operations & Growth Specialist (Paid in USD)',
    company: 'Athena Executive Management',
    location: 'Remote (Worldwide)',
    city: 'New York',
    state: 'NY',
    isRemote: true,
    category: 'Customer Support & Helpdesk',
    experienceLevel: 'Mid Level',
    salaryMin: 45000,
    salaryMax: 65000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'US Remote (Contractor/W-8BEN)',
    sponsorshipConfidence: 'high',
    description: 'Work directly alongside high-growth U.S. tech founders and venture executives. Manage executive communications, strategic scheduling, project workflows, and asynchronous reporting in USD.',
    requirements: [
      'Impeccable written and spoken English communication',
      'High organizational mastery and proactive problem-solving',
      'Proficiency with Slack, Notion, Google Workspace, and AI automation tools'
    ],
    skills: ['Executive Operations', 'Project Management', 'Notion', 'Google Workspace', 'Client Relations'],
    sourceUrl: 'https://www.athenago.com',
    atsType: 'workday',
    postedDate: new Date().toISOString(),
    isFeatured: false
  },
  {
    id: 'job-h1b-006',
    title: 'Machine Learning Research Specialist (Cap-Exempt H-1B Sponsor)',
    company: 'Broad Institute of MIT and Harvard',
    location: 'Cambridge, MA',
    city: 'Cambridge',
    state: 'MA',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Mid Level',
    salaryMin: 95000,
    salaryMax: 135000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'The Broad Institute is a 501(c)(3) research institute exempt from the annual H-1B lottery cap. Build deep learning models for genomic analysis and drug target discovery. Immediate year-round H-1B sponsorship.',
    requirements: [
      'Master’s or PhD in Computer Science, Bioinformatics, or Computational Biology',
      'Proficiency in Python, PyTorch/TensorFlow, and high-performance computing clusters',
      'Experience analyzing large-scale biological datasets'
    ],
    skills: ['Python', 'PyTorch', 'Genomics', 'Machine Learning', 'Bioinformatics'],
    sourceUrl: 'https://www.broadinstitute.org/careers',
    atsType: 'workday',
    postedDate: new Date().toISOString(),
    isFeatured: true
  },
  {
    id: 'job-h1b-007',
    title: 'Lead Cloud Infrastructure Architect (Cap-Exempt H-1B)',
    company: 'University of Texas at Austin',
    location: 'Austin, TX',
    city: 'Austin',
    state: 'TX',
    isRemote: false,
    category: 'Software & Tech',
    experienceLevel: 'Senior / Lead',
    salaryMin: 105000,
    salaryMax: 145000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'Cap-Exempt H-1B',
    sponsorshipConfidence: 'high',
    description: 'UT Austin sponsors non-lottery H-1B visas year-round for IT and engineering professionals. Architect secure multi-cloud environments supporting over 50,000 university researchers and faculty.',
    requirements: [
      'Bachelor’s or Master’s in Computer Science or related engineering field',
      'Demonstrated experience with enterprise cloud security and hybrid networking',
      'AWS / Azure Certified Solutions Architect'
    ],
    skills: ['AWS', 'Cloud Architecture', 'Terraform', 'Linux', 'Network Security'],
    sourceUrl: 'https://hr.utexas.edu/prospective/careers',
    atsType: 'workday',
    postedDate: new Date().toISOString(),
    isFeatured: false
  },
  {
    id: 'job-nurse-003',
    title: 'Critical Care ICU Registered Nurse (Schedule A Green Card Sponsoring)',
    company: 'Cleveland Clinic Health System',
    location: 'Cleveland, OH',
    city: 'Cleveland',
    state: 'OH',
    isRemote: false,
    category: 'Healthcare & Nursing',
    experienceLevel: 'Mid Level',
    salaryMin: 80000,
    salaryMax: 110000,
    salaryCurrency: 'USD',
    salaryPeriod: 'year',
    visaSponsorship: 'H-1B Sponsor',
    sponsorshipConfidence: 'high',
    description: 'Cleveland Clinic sponsors qualified international Registered Nurses for direct EB-3 Permanent Residency (Green Cards) with zero PERM labor delay. Full relocation package and licensing assistance provided.',
    requirements: [
      'BSN Degree from an accredited international nursing institution',
      'Passed NCLEX-RN examination or active CGFNS certification',
      'Minimum 18 months recent acute care ICU/Emergency experience'
    ],
    skills: ['ICU Nursing', 'Critical Care', 'NCLEX-RN', 'Patient Assessment', 'Ventilator Management'],
    sourceUrl: 'https://jobs.clevelandclinic.org',
    atsType: 'workday',
    postedDate: new Date().toISOString(),
    isFeatured: true
  },
];

let dynamicJobs: JobPosting[] = [...INITIAL_JOBS];

export function getJobsList(): JobPosting[] {
  return dynamicJobs;
}

export function addOrUpdateJobs(newJobs: JobPosting[]) {
  const existingMap = new Map<string, JobPosting>();
  dynamicJobs.forEach(j => existingMap.set(j.id, j));
  newJobs.forEach(j => existingMap.set(j.id, j));
  dynamicJobs = Array.from(existingMap.values());
  dynamicJobs.sort((a, b) => new Date(b.postedDate).getTime() - new Date(a.postedDate).getTime());
}

export function findJobById(id: string): JobPosting | undefined {
  return dynamicJobs.find(j => j.id === id);
}
