export interface CountryTreatyInfo {
  code: string;
  name: string;
  hasTreaty: boolean;
  treatyName: string;
  ftinName: string;
  ftinFormat: string;
  ftinRegex: string; // string representation of RegExp
  ftinDescription: string;
  serviceWithholdingRate: number; // usually 0% under Art 7 or Foreign Source
  royaltyWithholdingRate: number; // 0%, 5%, 10%, 15%, 30%
  serviceTreatyArticle: string;
  royaltyTreatyArticle: string;
  specialNotes?: string;
}

export const COUNTRIES_TREATY_DATA: CountryTreatyInfo[] = [
  {
    code: 'GB',
    name: 'United Kingdom',
    hasTreaty: true,
    treatyName: 'US-UK Income Tax Convention (2001/2003)',
    ftinName: 'Unique Taxpayer Reference (UTR) or National Insurance Number (NINO)',
    ftinFormat: '10 digits (UTR) or 2 letters + 6 digits + 1 letter (NINO)',
    ftinRegex: '^(\\d{10}|[A-CEGHJ-PR-TW-Z]{2}\\d{6}[A-D])$',
    ftinDescription: '10-digit UTR from HMRC or standard 9-character NINO format.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'CA',
    name: 'Canada',
    hasTreaty: true,
    treatyName: 'US-Canada Income Tax Convention',
    ftinName: 'Social Insurance Number (SIN) or Business Number (BN)',
    ftinFormat: '9 digits (SIN: 123456789 or BN: 123456789RC0001)',
    ftinRegex: '^(\\d{9}|\\d{9}[A-Z]{2}\\d{4})$',
    ftinDescription: '9-digit CRA Social Insurance Number or 15-character Business Number.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article VII (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article XII (Royalties) - 0% Rate (General/Copyright)'
  },
  {
    code: 'IN',
    name: 'India',
    hasTreaty: true,
    treatyName: 'US-India Double Tax Avoidance Agreement (DTAA)',
    ftinName: 'Permanent Account Number (PAN)',
    ftinFormat: '10 alphanumeric characters (e.g., ABCDE1234F)',
    ftinRegex: '^[A-Z]{5}\\d{4}[A-Z]$',
    ftinDescription: 'Issued by the Indian Income Tax Department. 5 uppercase letters, 4 digits, 1 uppercase letter.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 15,
    serviceTreatyArticle: 'Article 7 (Business Profits) / Article 15 / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties & Fees for Included Services) - 15% Rate'
  },
  {
    code: 'DE',
    name: 'Germany',
    hasTreaty: true,
    treatyName: 'US-Germany Double Taxation Convention',
    ftinName: 'Steuer-Identifikationsnummer (IdNr) or Steuernummer',
    ftinFormat: '11 digits (IdNr) or 10-13 digits (Steuernummer)',
    ftinRegex: '^(\\d{11}|\\d{10,13})$',
    ftinDescription: '11-digit Federal Tax ID or local Tax Number from the Finanzamt.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'FR',
    name: 'France',
    hasTreaty: true,
    treatyName: 'US-France Double Taxation Treaty',
    ftinName: 'Numéro Fiscal (SPI) or SIREN/SIRET',
    ftinFormat: '13 digits (SPI) or 9 digits (SIREN)',
    ftinRegex: '^(\\d{13}|\\d{9})$',
    ftinDescription: '13-digit individual tax number (SPI) from DGFIP or 9-digit SIREN for sole proprietorships.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'AU',
    name: 'Australia',
    hasTreaty: true,
    treatyName: 'US-Australia Income Tax Treaty',
    ftinName: 'Tax File Number (TFN) or Australian Business Number (ABN)',
    ftinFormat: '8-9 digits (TFN) or 11 digits (ABN)',
    ftinRegex: '^(\\d{8,9}|\\d{11})$',
    ftinDescription: '8 or 9-digit TFN from ATO or 11-digit ABN for registered sole contractors.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 5,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 5% Rate'
  },
  {
    code: 'BR',
    name: 'Brazil',
    hasTreaty: false,
    treatyName: 'No US-Brazil Double Tax Treaty (Foreign Source Rules Apply)',
    ftinName: 'Cadastro de Pessoas Físicas (CPF)',
    ftinFormat: '11 digits (e.g. 123.456.789-01)',
    ftinRegex: '^(\\d{11}|\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2})$',
    ftinDescription: '11-digit tax registry from Receita Federal do Brasil.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 30,
    serviceTreatyArticle: 'Foreign Source Income under IRC § 862(a)(3) (0% US Withholding if 100% offshore)',
    royaltyTreatyArticle: 'Non-Treaty Statutory Rate: 30% under IRC § 1441'
  },
  {
    code: 'PH',
    name: 'Philippines',
    hasTreaty: true,
    treatyName: 'US-Philippines Tax Treaty',
    ftinName: 'Taxpayer Identification Number (TIN)',
    ftinFormat: '9 to 12 digits (e.g., 123-456-789-000)',
    ftinRegex: '^(\\d{9}|\\d{12}|\\d{3}-\\d{3}-\\d{3}(-\\d{3})?)$',
    ftinDescription: '9 or 12-digit TIN issued by the Bureau of Internal Revenue (BIR).',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 15,
    serviceTreatyArticle: 'Article 8 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 13 (Royalties) - 15% Rate'
  },
  {
    code: 'PK',
    name: 'Pakistan',
    hasTreaty: true,
    treatyName: 'US-Pakistan Double Taxation Convention',
    ftinName: 'National Tax Number (NTN) or CNIC',
    ftinFormat: '7 digits + 1 digit (NTN: 1234567-8) or 13 digits (CNIC)',
    ftinRegex: '^(\\d{7}-?\\d{1}|\\d{13}|\\d{5}-\\d{7}-\\d{1})$',
    ftinDescription: 'Issued by the Federal Board of Revenue (FBR) or 13-digit NADRA CNIC.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article III (Industrial/Commercial Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article VIII (Copyright/Patent Royalties) - 0% Rate'
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    hasTreaty: true,
    treatyName: 'US-Bangladesh Double Taxation Treaty (2004)',
    ftinName: 'Electronic Tax Identification Number (e-TIN)',
    ftinFormat: '12 digits (e.g., 123456789012)',
    ftinRegex: '^\\d{12}$',
    ftinDescription: '12-digit e-TIN issued by the National Board of Revenue (NBR).',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 10,
    serviceTreatyArticle: 'Article 7 (Business Profits) / Article 15 / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 10% Rate'
  },
  {
    code: 'NG',
    name: 'Nigeria',
    hasTreaty: false,
    treatyName: 'No US-Nigeria Double Tax Treaty (Foreign Source Rules Apply)',
    ftinName: 'Tax Identification Number (TIN) or NIN',
    ftinFormat: '10 to 14 digits (TIN) or 11 digits (NIN)',
    ftinRegex: '^(\\d{10,14}|\\d{11})$',
    ftinDescription: 'TIN issued by FIRS/JTB or 11-digit National Identification Number (NIN).',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 30,
    serviceTreatyArticle: 'Foreign Source Income under IRC § 862(a)(3) (0% US Withholding if 100% offshore)',
    royaltyTreatyArticle: 'Non-Treaty Statutory Rate: 30% under IRC § 1441'
  },
  {
    code: 'KE',
    name: 'Kenya',
    hasTreaty: false,
    treatyName: 'No US-Kenya Double Tax Treaty (Foreign Source Rules Apply)',
    ftinName: 'KRA PIN (Personal Identification Number)',
    ftinFormat: '11 alphanumeric characters (e.g., A012345678X)',
    ftinRegex: '^[A-Z]\\d{9}[A-Z]$',
    ftinDescription: '11-character PIN issued by Kenya Revenue Authority (KRA). Starts with letter, 9 digits, ends with letter.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 30,
    serviceTreatyArticle: 'Foreign Source Income under IRC § 862(a)(3) (0% US Withholding if 100% offshore)',
    royaltyTreatyArticle: 'Non-Treaty Statutory Rate: 30% under IRC § 1441'
  },
  {
    code: 'MX',
    name: 'Mexico',
    hasTreaty: true,
    treatyName: 'US-Mexico Income Tax Treaty',
    ftinName: 'Registro Federal de Contribuyentes (RFC)',
    ftinFormat: '13 alphanumeric characters (e.g. ABCD800101XYZ)',
    ftinRegex: '^[A-Z&Ñ]{4}\\d{6}[A-Z0-9]{3}$',
    ftinDescription: '13-character RFC with homoclave issued by the Servicio de Administración Tributaria (SAT).',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 10,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 10% Rate'
  },
  {
    code: 'JP',
    name: 'Japan',
    hasTreaty: true,
    treatyName: 'US-Japan Income Tax Treaty',
    ftinName: 'Individual Number (My Number)',
    ftinFormat: '12 digits (e.g. 123456789012)',
    ftinRegex: '^\\d{12}$',
    ftinDescription: '12-digit Individual Number issued by the Japanese National Tax Agency.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'KR',
    name: 'South Korea',
    hasTreaty: true,
    treatyName: 'US-Korea Tax Treaty',
    ftinName: 'Resident Registration Number (RRN) / Business Tax ID',
    ftinFormat: '13 digits (RRN: 123456-1234567) or 10 digits (Biz ID)',
    ftinRegex: '^(\\d{6}-?\\d{7}|\\d{10}|\\d{3}-\\d{2}-\\d{5})$',
    ftinDescription: '13-digit National Tax ID/RRN from the National Tax Service (NTS).',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 10,
    serviceTreatyArticle: 'Article 8 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 14 (Royalties) - 10% Rate'
  },
  {
    code: 'PL',
    name: 'Poland',
    hasTreaty: true,
    treatyName: 'US-Poland Income Tax Treaty',
    ftinName: 'PESEL or NIP',
    ftinFormat: '11 digits (PESEL) or 10 digits (NIP)',
    ftinRegex: '^(\\d{11}|\\d{10}|\\d{3}-\\d{3}-\\d{2}-\\d{2})$',
    ftinDescription: '11-digit PESEL for individuals or 10-digit NIP for business contractors.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 10,
    serviceTreatyArticle: 'Article 8 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 13 (Royalties) - 10% Rate'
  },
  {
    code: 'IL',
    name: 'Israel',
    hasTreaty: true,
    treatyName: 'US-Israel Income Tax Treaty',
    ftinName: 'Teudat Zehut (Identity Number)',
    ftinFormat: '9 digits (e.g. 123456789)',
    ftinRegex: '^\\d{9}$',
    ftinDescription: '9-digit Israeli ID number registered with the Israel Tax Authority.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 10,
    serviceTreatyArticle: 'Article 8 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 14 (Royalties) - 10% Rate (Copyright/Patent)'
  },
  {
    code: 'IE',
    name: 'Ireland',
    hasTreaty: true,
    treatyName: 'US-Ireland Double Taxation Convention',
    ftinName: 'Personal Public Service Number (PPSN)',
    ftinFormat: '7 digits + 1 or 2 letters (e.g., 1234567T or 1234567WA)',
    ftinRegex: '^\\d{7}[A-W][A-W]?$',
    ftinDescription: '8 or 9-character PPS Number issued by the Revenue Commissioners.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'NL',
    name: 'Netherlands',
    hasTreaty: true,
    treatyName: 'US-Netherlands Income Tax Convention',
    ftinName: 'Burgerservicenummer (BSN) or RSIN',
    ftinFormat: '9 digits (e.g., 123456789)',
    ftinRegex: '^\\d{8,9}$',
    ftinDescription: '8 or 9-digit BSN issued by the Belastingdienst.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 13 (Royalties) - 0% Rate'
  },
  {
    code: 'ES',
    name: 'Spain',
    hasTreaty: true,
    treatyName: 'US-Spain Double Taxation Treaty',
    ftinName: 'Número de Identificación Fiscal (NIF/NIE)',
    ftinFormat: '8 digits + 1 letter (NIF) or 1 letter + 7 digits + 1 letter (NIE)',
    ftinRegex: '^(\\d{8}[A-Z]|[XYZ]\\d{7}[A-Z])$',
    ftinDescription: '9-character NIF/NIE issued by the Agencia Tributaria.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'IT',
    name: 'Italy',
    hasTreaty: true,
    treatyName: 'US-Italy Income Tax Convention',
    ftinName: 'Codice Fiscale (CF)',
    ftinFormat: '16 alphanumeric characters (e.g., RSSMRA85M01H501Z)',
    ftinRegex: '^[A-Z]{6}\\d{2}[A-EHLMPR-T]\\d{2}[A-Z]\\d{3}[A-Z]$',
    ftinDescription: '16-character alphanumeric code issued by the Agenzia delle Entrate.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% to 5% Rate'
  },
  {
    code: 'SG',
    name: 'Singapore',
    hasTreaty: false,
    treatyName: 'No US-Singapore Double Tax Treaty (Foreign Source Rules Apply)',
    ftinName: 'NRIC / FIN / UEN',
    ftinFormat: '9 alphanumeric characters (e.g. S1234567A)',
    ftinRegex: '^[STFGM]\\d{7}[A-Z]$',
    ftinDescription: '9-character NRIC/FIN registered with the Inland Revenue Authority of Singapore (IRAS).',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 30,
    serviceTreatyArticle: 'Foreign Source Income under IRC § 862(a)(3) (0% US Withholding if 100% offshore)',
    royaltyTreatyArticle: 'Non-Treaty Statutory Rate: 30% under IRC § 1441'
  },
  {
    code: 'ZA',
    name: 'South Africa',
    hasTreaty: true,
    treatyName: 'US-South Africa Tax Treaty',
    ftinName: 'Income Tax Reference Number',
    ftinFormat: '10 digits (e.g. 1234567890)',
    ftinRegex: '^\\d{10}$',
    ftinDescription: '10-digit tax reference number issued by SARS.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 0,
    serviceTreatyArticle: 'Article 7 (Business Profits) / IRC § 862',
    royaltyTreatyArticle: 'Article 12 (Royalties) - 0% Rate'
  },
  {
    code: 'VN',
    name: 'Vietnam',
    hasTreaty: false,
    treatyName: 'No US-Vietnam Double Tax Treaty in effect (Foreign Source Rules Apply)',
    ftinName: 'Tax Identification Number (Mã số thuế - MST)',
    ftinFormat: '10 or 13 digits (e.g. 0123456789)',
    ftinRegex: '^(\\d{10}|\\d{10}-\\d{3})$',
    ftinDescription: '10-digit or 13-digit personal tax code issued by the General Department of Taxation.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 30,
    serviceTreatyArticle: 'Foreign Source Income under IRC § 862(a)(3) (0% US Withholding if 100% offshore)',
    royaltyTreatyArticle: 'Non-Treaty Statutory Rate: 30% under IRC § 1441'
  },
  {
    code: 'OTHER',
    name: 'Other Non-Treaty Country',
    hasTreaty: false,
    treatyName: 'Standard IRC Statutory Provisions (Non-Treaty)',
    ftinName: 'National Tax Identification Number (TIN)',
    ftinFormat: 'National Tax ID format in country of residence',
    ftinRegex: '^.{3,25}$',
    ftinDescription: 'Official taxpayer identification number issued by local tax authorities.',
    serviceWithholdingRate: 0,
    royaltyWithholdingRate: 30,
    serviceTreatyArticle: 'Foreign Source Income under IRC § 862(a)(3) (0% US Withholding if 100% offshore)',
    royaltyTreatyArticle: 'Non-Treaty Statutory Rate: 30% under IRC § 1441'
  }
];
